---

- name: add repo
  script: rabbit-erlang.sh

- name: install socat
  yum :
   name: socat
   state: present

- name: download elrang centos
  command: "{{ item }}  chdir=/home/quynhnv/src/"
  with_items:
    - wget http://github.com/rabbitmq/erlang-rpm/releases/download/v20.1.2/erlang-20.1.2-1.el7.centos.x86_64.rpm
    - wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.6/rabbitmq-server-3.7.6-1.el7.noarch.rpm
- name: install erlang  
  yum: 
    name: /home/quynhnv/src/erlang-20.1.2-1.el7.centos.x86_64.rpm 
    state: present
- name: install rabbitmq
  yum:
   name: /home/quynhnv/src/rabbitmq-server-3.7.6-1.el7.noarch.rpm
   state: present
- include: service.yml

- name: enable rabbitmq-server plugin
  include_tasks: enable-rabbitmq.yml

- name: add user
  script: adduser.sh 

- include: config-rabbitmq.yml
